import '../styles/globals.css'
// import "../../public/styles/style.css"

import Layout from '../components/Layout';
import Head from 'next/head'
import { useState } from 'react';


export default function App({ Component, pageProps }) {
  const [ loginuser, setLoginUser ] = useState(null);
  return (
    <>
      <Head>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/style.css" /> */}
      </Head>
      <Layout style={{ fontFamily: '851マカポップ' }} loginuser = {loginuser} setLoginUser = {setLoginUser}>
        <Component {...pageProps} loginuser = {loginuser} setLoginUser = {setLoginUser} />
      </Layout>
    </>
  )
}
