import '@/styles/globals.css'
import Layout from '@/compnents/Layout';
import Head from 'next/head'
import { useState } from 'react';


export default function App({ Component, pageProps }) {
  const [ loginuser, setLoginUser ] = useState('loginuser');
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Component {...pageProps} loginuser = {loginuser} setLoginUser = {setLoginUser} />
      </Layout>
    </>
  )
}
